apiVersion: v1
kind: Service
metadata:
  name: sift-persist
  labels:
    app: sift-persist
spec:
  ports:
    - name: port-8091
      port: 8091
    - name: port-8092
      port: 8092
    - name: port-11210
      port: 11210
  selector:
    app: sift-persist-pod
  type: ClusterIP