apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sift-persist-ingress
  namespace: opolo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: admin.prod.quiinsfelicity.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal-admin
            port:
              number: 3000
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080