apiVersion: v1
kind: Secret
metadata:
  name: opolo-credentials
type: Opaque
data:
  filebeat: bWFhc0A4ODgK
  keycloak-db: UGE1NXcwcmQK
  keycloak-admin: UGE1NXcwcmQK
  postgress-db: U1g2TlpyRDdxRndyeGZSbgo=
  postgress-url: cG9zdGdyZXM6Ly9vcG9sb3BvcnRhbHVzZXI6U1g2TlpyRDdxRndyeGZSbkBwb3N0Z3Jlc3FsOjU0MzIvcnR1RXlieFlDaGptVlliCg==
  kibana: bWFhc0A4ODgK
  redis: cGFzc3cwcmQK
  portal-admin: c2lmdEAxMjMK
  aws-secret: OUgzUnBpVkxCNVVERzZCT0twTXM0R09tMXFGU1FjMnlXdFVwdk1BZwo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgres-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pod
  template:
    metadata:
      labels:
        app: postgres-pod
    spec:
      imagePullSecrets:
      - name: regcred
      hostname: postgresql
      containers:
      - image: chakkarinsom/siftmanage:postgres-1
        imagePullPolicy: Always
        name: postgresql
        env:
        - name: POSTGRES_USER
          value: opoloportaluser
        - name: POSTGRES_DB
          value: rtuEybxYChjmVYb
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opolo-credentials
              key: postgress-db
        - name: KEYCLOCK_IPANDPORT
          value: "https://admin.prod.quiinsfelicity.shop"
        - name: OPOLO_ADMIN_IPANDPORT
          value: "https://admin.prod.quiinsfelicity.shop"
        - name: DOMAIN_NAME
          value: "https://admin.prod.quiinsfelicity.shop"
        ports:
        - containerPort: 5432
          name: postgresql
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 100m
