apiVersion: v1
kind: Service
metadata:
  name: gateway-designtime
  labels:
    app: gateway-designtime-pod
spec:
  ports:
    - port: 10040
  selector:
    app: gateway-designtime-pod
  type: ClusterIP