apiVersion: apps/v1
kind: Deployment
metadata:
  name: sift-es
  labels:
    app: sift-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sift-es
  template:
    metadata:
      labels:
        app: sift-es
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: sift-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: xpack.security.enabled
          value: "false"
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms2G -Xmx4G"
        resources:
          requests:
            memory: "2Gi"
            cpu: 500m
          limits:
            memory: "5Gi"
            cpu: 1000m
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: ebs-es-pvc