apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-ds-configs
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - ${LOG_PATH}.log
      fields:
        service_name: ${SERVICE_NAME}
        log_type: logs
      fields_under_root: true
    - type: log
      paths:
        - ${LOG_PATH}_report.log
      fields:
        service_name: ${SERVICE_NAME}
        log_type: report
      fields_under_root: true

    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOST}:9200"]
      username: "filebeat_user"
      password: "maas@888"
      indices:
        - index: "app-%{[log_type]}-%{+yyyy.MM.dd}"
          when.equals:
            log_type: logs
        - index: "app-%{[log_type]}-%{+yyyy.MM.dd}"
          when.equals:
            log_type: report
      setup.template.enabled: true
      setup.template.overwrite: true
      setup.template.name: "app-*"
      setup.template.pattern: "app-*"
      setup.template.settings:
        index:
          number_of_shards: 1
          number_of_replicas: 1
      ilm.enabled: false
      setup.ilm.enabled: false
    ilm.enabled: false
    setup.ilm.enabled: false
    ilm.policy_name: "null"
    setup.template.name: "app-*"
    setup.template.pattern: "app-*"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sift-es
  labels:
    app: sift-es
    resourceType: ELK
    resourceName: Elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sift-es
  template:
    metadata:
      labels:
        app: sift-es
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: sift-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: xpack.security.enabled
          value: "false"
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms2G -Xmx4G"
        resources:
          requests:
            memory: "2Gi"
            cpu: 500m
          limits:
            memory: "5Gi"
            cpu: 1000m
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: ebs-es-pvc