apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmsapi-master-pod
    resourceName: cmsapi-svc
    resourceType: portal
  name: cmsapi
spec:
  ports:
  - name: cmsapi
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: cmsapi-master-pod
  type: ClusterIP